### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by ggabriel96** [risujin/cellwriter#2]
Hello there, how are you doing?
Can anyone provide a guide for building on Windows or a ready-to-use binary? I've just tried building it on my machine with Cygwin (and apparently I got all the dependencies set up) but when I click on the `.exe` a console pops up and immediately closes. The application itself does not show up and I can't see any message on any command prompt I try to run it with. Is there anything I can do? I'm on Windows 10 x64.

**Comment by risujin** [comment]
Hi Gabriel,

I've never tried building CW on Windows, I'm not sure that the XTest library it relies on will work as expected. I'm afraid I really don't know how to get it working...

If you need handwriting recognition services on Windows however, the Windows handwriting tools are much superior. They were the original inspiration for CW in fact. Sounds like it's pretty straightforward to setup:
https://www.howtogeek.com/297443/how-to-use-handwriting-input-on-windows-10/

**Comment by ggabriel96** [comment]
Hi Michael!

Oh, I see. Yeah, I've been using the Windows Handwriting and it's pretty good indeed, but is almost useless when not strictly writing text (I mean e-mail addresses or words mixed with symbols, etc.). I wanted some kind of char-by-char recognition and CellWriter is the best app I could find for this task. It's sad, but no problem. It's not THAT important.

Thank you very much for you reply, anyways :)
